export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "cctv-bullet-01",
    slug: "dahua-2mp-hdcvi-ir-bullet-camera",
    title: "Dahua 2MP HDCVI IR Bullet Camera (Smart Night Vision)",
    price: 49,
    rating: 5,
    description: "High-definition 1080P outdoor weatherproof security camera with Smart IR and IP67 protection.",
    mainImage: "/dh-hac-b4a21-vf-2mp-hdcvi-ir-bullet-camera-500x500-1.png",
    manufacturer: "Dahua",
    categoryId: "cctv-security",
    category: { name: "cctv-security" },
    inStock: 25,
  },
  {
    id: "cctv-dome-02",
    slug: "hikvision-360-turret-dome-camera",
    title: "Hikvision 360° AI Eyeball Turret Dome Camera",
    price: 65,
    rating: 5,
    description: "Commercial indoor/outdoor turret dome with 360 wide-angle surveillance, motion sensor, and night guard.",
    mainImage: "/cat-cctv-security.png",
    manufacturer: "Hikvision",
    categoryId: "cctv-security",
    category: { name: "cctv-security" },
    inStock: 18,
  },
  {
    id: "charger-pd-03",
    slug: "needyzone-20w-fast-pd-typec-charger",
    title: "NeedyZone 20W Fast PD Dual USB-C Wall Charger",
    price: 19,
    rating: 5,
    description: "Ultra-compact GaN fast power delivery adapter compatible with iPhone, Android, and tablets.",
    mainImage: "/dept-charger.jpg",
    manufacturer: "NeedyZone",
    categoryId: "mobile-chargers",
    category: { name: "mobile-chargers" },
    inStock: 50,
  },
  {
    id: "cable-braided-04",
    slug: "needyzone-100w-braided-typec-cable",
    title: "100W Nylon Braided Ultra-Fast Type-C to Type-C Cable",
    price: 12,
    rating: 5,
    description: "Heavy-duty 2-meter fast charging and 480Mbps data transfer cable with reinforced alloy connectors.",
    mainImage: "/dept-cables.jpg",
    manufacturer: "NeedyZone",
    categoryId: "data-cables",
    category: { name: "data-cables" },
    inStock: 80,
  },
  {
    id: "switch-digital-05",
    slug: "smart-digital-touch-switch-board-4gang",
    title: "Smart Digital Touch Switch Board (WiFi / App Controlled)",
    price: 35,
    rating: 5,
    description: "Tempered crystal glass touch control wall panel compatible with Alexa, Google Home, and smartphone app.",
    mainImage: "/dept-smartswitch.jpg",
    manufacturer: "NeedyZone",
    categoryId: "digital-switches",
    category: { name: "digital-switches" },
    inStock: 30,
  },
  {
    id: "power-strip-06",
    slug: "surge-protected-smart-power-strip-surge-guard",
    title: "Heavy-Duty Surge Protected 6-Socket Power Extension Board",
    price: 28,
    rating: 5,
    description: "Master surge protection extension strip with 4 USB quick-charging ports and fireproof casing.",
    mainImage: "/dept-powerstrip.jpg",
    manufacturer: "NeedyZone",
    categoryId: "power-strips",
    category: { name: "power-strips" },
    inStock: 40,
  },
  {
    id: "cctv-pro-07",
    slug: "pro-wireless-outdoor-ip-cctv-camera",
    title: "Pro 4K Wireless Outdoor PTZ Security CCTV Camera",
    price: 89,
    rating: 5,
    description: "Motorized pan-tilt-zoom wireless outdoor camera with two-way audio, spotlight color night vision, and cloud storage.",
    mainImage: "/hero-cctv-trio-transparent.png",
    manufacturer: "NeedyZone",
    categoryId: "cctv-security",
    category: { name: "cctv-security" },
    inStock: 15,
  },
  {
    id: "gadgets-08",
    slug: "dual-band-gigabit-wifi-mesh-router",
    title: "NeedyZone Dual-Band Gigabit WiFi 6 Mesh Security Router",
    price: 59,
    rating: 5,
    description: "Ultra-fast WiFi 6 router designed for multi-camera CCTV live streams, low-latency streaming, and whole-home coverage.",
    mainImage: "/dept-networking.jpg",
    manufacturer: "NeedyZone",
    categoryId: "networking-devices",
    category: { name: "networking-devices" },
    inStock: 22,
  },
];
